apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-overview.name" . }}
  namespace: {{ include "rbac-overview.namespace" . }}
  labels:
    {{- include "rbac-overview.labels" . | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.service.servingCertSecretName }}
spec:
  ports:
    - name: {{ printf "%d-tcp" (int .Values.service.port) }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "rbac-overview.selectorLabels" . | nindent 4 }}
  type: ClusterIP
